### ISSUE TITLE
vi har flere sub'er som har 0 references

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidationAddIn#116]
sub'en kravFlerspråklighetPakke i kravFlerspråklighetPakke.vb må kalles fra hovedløkka der den pt. mangler kobling.

**Comment by toreJohnsen** [comment]
SOSIModelValidation\krav6.vb:33 Function 'isLCName' is never used (?)
SOSIModelValidation\reqGeneralFeature.vb:42 Sub 'reqGeneralFeature' is never used (muligens false positive)
SOSIModelValidation\requirement16.vb:21 Sub 'requirement16' is never used (method)
SOSIModelValidation\reqUMLDocumentation.vb:30 Sub 'reqUMLDocumentation' is never used (method, constraint)

SOSIModelValidation\reqUMLIntegration.vb:145 Local variable 'parentPackageIsApplicationSchema' is only assigned but its value is never used (ville ikke røre denne før vi har sjekket det ut at den ikke brukes ett eller annet sært sted)

**Comment by magnusKarge** [comment]
ferdig implementert i #120
