### ISSUE TITLE
/krav/SOSI-modellregister/applikasjonsskjema/versjonsnummer

### ISSUE THREAD

**Issue by toreJohnsen** [kartverket/SOSIModelValidationAddIn#123]
Dette kravet er endret til å bare gjelde gyldige modeller.

Rutinen må skrives om til å kun teste der SOSI_modellstatus = gyldig

Hvis utkast testen ligger i samme rutine må den fortsatt kjøres der SOSI_modellstatus = utkast

**Comment by magnusKarge** [comment]
skal ses i sammenheng med #135

**Comment by magnusKarge** [comment]
fixed in #144
