### ISSUE TITLE
tilpassing til bruk i fkb-revisjon

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#129]
Pseudokode For å tilpasse sosi model validation versjon 1,1 til å kunne brukes mot det pågående fkb-revisjonsarbeidet
2021-03-06

Fixes to krav/visualisering:

fullyShownInDiagram.vb
----------------------
    Function showingAttributes(theElement, theDiagram, ByRef message)
        showingAttributes = True
        If theElement.Attributes.Count <> 0 And InStr(1, theDiagram.ExtendedStyle, "HideAtts=1") <> 0 And Not elementAttrShownInDiagram(theElement, theDiagram) Then
            message = message & " diagram has turned off attribute visibility"
            showingAttributes = False

   Function elementAttrShownInDiagram(theElement, theDiagram)
        Dim j, eID, dID, duid
        elementAttrShownInDiagram = False
        '   Output("Debuggg0a  theDiagram.ExtendedStyle: " & theDiagram.ExtendedStyle)
        '    Output("Debuggg0b  theDiagram.StyleEX: " & theDiagram.StyleEX)
        For j = 0 To diaoList.Count - 1
            dID = diaoList.GetByIndex(j)
            If dID = theDiagram.DiagramID Then
                'the diagram object is owned by the current diagram
                eID = diaeList.GetByIndex(j)
                If eID = theElement.ElementID Then
                    'the element is shown by this diagram object, but are its attributes shown?
                    Dim diaobj As EA.DiagramObject
                    For Each diaobj In theDiagram.DiagramObjects
                        '        Output("Debuggg1 diaobj.InstanceID + diaoList.GetKey(j):" & diaobj.InstanceID & "  " & diaoList.GetKey(j))
                        If diaobj.InstanceID = diaoList.GetKey(j) Then
                            '            Output("Debuggg2  diaobj.Style: " & diaobj.Style)
                            duid = Mid(diaobj.Style, InStr(1, diaobj.Style, "DUID=") + 5, 8)  ' TBD: should be read not 8 chars but until next ;
                            '    Output("Debuggg3  duid: " & duid)
                            If InStr(1, theDiagram.StyleEX, duid & "=Att=1:") <> 0 Then
                                elementAttrShownInDiagram = True
                            End If
                        End If
                    Next
                End If
            End If
        Next
    End Function

Function showingRoles(theElement, theDiagram, ByRef message)
        showingRoles = True

        If theElement.Connectors.Count <> 0 And InStr(1, theDiagram.ExtendedStyle, "HideRel=1") <> 0 Then
            message = message & " diagram has turned off relationship visibility"
            showingRoles = False
        Else
            ' find connectors and see whether the roles (opposite of the class) are shown in this diagram
            ' NB: this Else needs more testing !
            For Each connector In theElement.Connectors
                If connector.Type <> "Generalization" And connector.Type <> "Realisation" Then
                    Output("Debug:  Class [" & theElement.Name & "] [" & theElement.ElementID & "] Client [" & connector.ClientEnd.Role & "] [" & connector.ClientID & "] Supplier [" & connector.SupplierEnd.Role & "] [" & connector.SupplierID & "]")

                    If connector.ClientEnd.Role <> "" And connector.SupplierID = theElement.ElementID And theRepository.GetElementByID(connector.ClientID).Type = "Class" Then
                        If Not connectorShownInDiagram(connector, theDiagram) Then
                            message = message & " diagram is not showing role [" & connector.ClientEnd.Role & "]"
                            showingRoles = False
                        End If
                    End If
                    If connector.SupplierEnd.Role <> "" And connector.ClientID = theElement.ElementID And theRepository.GetElementByID(connector.SupplierID).Type = "Class" Then
                        If Not connectorShownInDiagram(connector, theDiagram) Then
                            message = message & " diagram is not showing role [" & connector.SupplierEnd.Role & "]"
                            showingRoles = False
                        End If
                    End If
                    ' TBD
                End If
            Next
        End If
    End Function
    
    Function connectorShownInDiagram(theConnector, theDiagram)
        Dim j, cID, dID
        connectorShownInDiagram = False
        Output("DebugggL diaolList.Count - diacList.Count: " & dialList.Count & " - " & diacList.Count)
        For j = 0 To dialList.Count - 1
            dID = dialList.GetByIndex(j)
            If dID = theDiagram.DiagramID Then
                'the diagram list is owned by the current diagram
                cID = diacList.GetByIndex(j)
                If cID = theConnector.ConnectorID Then
                    'the connector is shown by this diagram link
                    Output("DebugggC theDiagram.Name - theConnector.ConnectorID:" & theDiagram.Name & " - " & theConnector.ConnectorID)
                    Dim dialink As EA.DiagramLink
                    For Each dialink In theDiagram.DiagramLinks
                        If dialink.InstanceID = diacList.GetKey(j) Then
                            Output("Debuggg2C  dialink.Style: " & dialink.Style)
                        End If

                    Next

                    Output("DebugggD theDiagram.Name - theConnector.ConnectorID:" & theDiagram.Name & " - " & theConnector.ConnectorID)
                    connectorShownInDiagram = True
                End If
            End If
        Next
    End Function    

 Sub gatherDiagamsInPackageClear()
        diagramList.Clear()
        diaoList.Clear()
        diaeList.Clear()
        dialList.Clear()
        diacList.Clear()

    End Sub

    Sub gatherDiagamsInPackage(thePackage)

        Dim diagram As EA.Diagram
        Dim diagramObject As EA.DiagramObject
        Dim diagramLink As EA.DiagramLink

        For Each diagram In thePackage.diagrams

Slakke på krava?
                        '                    If UCase(Mid(dname, 1, 12)) = "HOVEDDIAGRAM" Or UCase(Mid(dname, 1, 16)) = "OVERSIKTSDIAGRAM" Then

ModelValidation.vb
---------------------
            Call reqUMLProfileLoad()
            Call gatherDiagamsInPackageClear()
            Call gatherDiagamsInPackage(thePackage)

. . .
utkommentert integration+17+21 i påvente av bruk av testen under.

To go into reqUMLProfile.vb
-----------------------------

    Function isWellKnownType(typename)
        'NB needs to be initialized, will not run independently
        isWellKnownType = False
        If CoreTypes.IndexOf(typename, 0) <> -1 Then
            isWellKnownType = True
        Else
            If ExtensionTypes.IndexOf(typename, 0) <> -1 Then
                isWellKnownType = True
            Else
                If ProfileTypes.IndexOf(typename, 0) <> -1 Then
                    isWellKnownType = True
                Else
                    If NationalTypes.IndexOf(typename, 0) <> -1 Then
                        isWellKnownType = True
                    End If
                End If
            End If
        End If

    End Function

kravVisualisering.vb
---------------------

Fixes to krav/16  exclude associations To Boundary etc.

requirement16.vb
-----------------

       For Each connector In theElement.Connectors
            If connector.Type <> "Generalization" And connector.Type <> "Realisation" Then
                'Output("Debug:  Class [" & theElement.Name & "] [" & theElement.ElementID & "] Client [" & connector.ClientEnd.Role & "] [" & connector.ClientID & "] Supplier [" & connector.SupplierEnd.Role & "] [" & connector.SupplierID & "]")

                If connector.ClientEnd.Role <> "" And connector.SupplierID = theElement.ElementID And theRepository.GetElementByID(connector.ClientID).Type = "Class" Then
                    'Output("Debug:  Class [" & theElement.Name & "] [" & theElement.ElementID & "] ClientEndRole [" & connector.ClientEnd.Role & "]  Client end type  [" & theRepository.GetElementByID(connector.ClientID).Type & "]")
                    If PropertyNames.IndexOf(UCase(connector.ClientEnd.Role), 0) <> -1 Then
                        Output("Error: Class [«" & theElement.Stereotype & "» " & theElement.Name & "] has non-unique role property names [" & connector.ClientEnd.Role & "]. [/krav/16]")
                        errorCounter += 1
                    Else
                        PropertyNames.Add(UCase(connector.ClientEnd.Role))
                    End If
                End If
                If connector.SupplierEnd.Role <> "" And connector.ClientID = theElement.ElementID And theRepository.GetElementByID(connector.SupplierID).Type = "Class" Then
   
Fixes to krav/21  exeptions for basic types

Add somewhere:

And Not isWellKnownType(datatype.Name)

Sjekker mot : Real -> til : Flate -> via : GM_Curve -> etc.

**Comment by magnusKarge** [comment]
solved in #134
