### ISSUE TITLE
sjekk på ekstern kodeliste tar ikke https-urler

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#132]
Det ser ut som om sjekk på url for ekstern kodeliste gir warning dersom det er en https-url.  Warningen forsvinner dersom man forandrer til http.

**Comment by magnusKarge** [comment]
dette gjelder mplementasjon av /krav/eksternKodeliste

**Comment by aatjora** [comment]
Fikset ved pullrequest #148
