### ISSUE TITLE
feil i /krav/SOSI-modellregister/applikasjonsskjema/versjonsnummer

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#135]
falsk positiv hvis det er uventede tegn (som en ekstra bindestrek eller underscore ?) i navnet.
![ending-in-version-number-Image4](https://user-images.githubusercontent.com/15031590/120826733-0a463080-c55b-11eb-9642-a5d6aec92700.png)

**Comment by magnusKarge** [comment]
ikke falsk positiv, men teksten i feilmeldingen må tilpasses slik at brukeren forstår hva som skal tilpasses. I dette tilfellet dreier det seg mest sannsynlig om feil format som har "_" der det skal være "-". Ta med formateksempel i feilmeldingsteksten: Format: <navn>-<versjonsnummer>

**Comment by magnusKarge** [comment]
fixed in #144

**Comment by KentJonsrud** [comment]
fix confirmed
