### ISSUE TITLE
SOSI_modellstatus utkastOgSkjult må være lov i /krav/SOSI-modellregister/applikasjonsskjema/standard/pakkenavn/utkast

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#136]
Error: Package [«ApplicationSchema» FKB-Bygning-5.0-Utkast2021-06-08] has Utkast as part of the name, but the tag [SOSI_modellstatus] has the value [utkastOgSkjult]. Expected value [utkast].

**Comment by magnusKarge** [comment]
hvilket krav er det igjen? savner referanse i feilmeldingen. Uansett, jeg kan tenke meg en lignende feilmelding ("...Expected value [utkast] or [utkastOgSkjult].") for alt som har utkast i pakkenavnet, men ikke en av utkast-statusene. Gitt at det passer med selve kravteksten.

**Comment by magnusKarge** [comment]
tilpasser testen slik at lovlig verdi i standarden "utkastOgSkjult" ikke gir feil i en setting der pakkenavnet inneholder "utkast". samtidig skal alle andre verdier enn [utkast] eller [utkastOgSkjult] trigge denne feilmeldingen

**Comment by KentJonsrud** [comment]
fixed in #145
