### ISSUE TITLE
Ny UML-profil med tomme tagger må ikke gi feilmelding

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#137]
Error: Class [«FeatureType» Fellesegenskaper] tag [description] has a value [] with wrong structure.  Expected structure: "{Name}"@{language}. [/krav/flerspråklighet/element]

**Comment by magnusKarge** [comment]
må ses i sammenheng med #133

**Comment by KentJonsrud** [comment]
fixed in #148
