### ISSUE TITLE
bør fjerne anbefalingen i meldingen fra /krav/15

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#138]
Error: Class [«featureType» Bygningsavgrensning] has found illegal stereotype «topo» on association named []. Recommended to use the script "endreTopoAssosiasjonTilRestriksjon". [/krav/15]

**Comment by magnusKarge** [comment]
Støtter at siste delen "Recommended to use the script ." fjernes. Den generer uønskede avhengigheter til rammene rundt (EA-versjoner, gamle script...).

**Comment by KentJonsrud** [comment]
fixed in #148
