### ISSUE TITLE
tomme definisjoner bør ikke trigge /anbefaling/3

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#141]
nemlig

**Comment by magnusKarge** [comment]
gjelder egentlig anbefaling/3 i standarden som feilaktig er implementert med referanse til anbefaling/6

ellers enig i at tomme definisjoner ikke skal trigge anbefaling/3 fra standarden

**Comment by magnusKarge** [comment]
tom er i dette tilfelle ""

**Comment by KentJonsrud** [comment]
fixed in #149
