### ISSUE TITLE
feil ifm. well known types

### ISSUE THREAD

**Issue by magnusKarge** [kartverket/SOSIModelValidationAddIn#142]
I #134 ble det gjort tilpassninger i reqUMLProfile.vb slik at det nå testes mot en liste well known types via en function IsWellKnownType. Denne filtrerer bort en del støy.

Det samme bør gjøres ifm. krav/21 (requirement21.vb), krav/17 (requirement17.vb) og /req/UML/integration (reqUMLIntegration.vb) for å unngå feilmeldinger som i eksemplene nedenfor (fra en test med Landskapsarkitektur 5.0):

Error: Missing dependency for package [«applicationSchema» Datatyper_19103CSLv4.0] containing external referenced class [«dataType» CharacterString] [/req/UML/integration]
Error: Missing dependency for package [«applicationSchema» Datatyper_19103CSLv4.0] containing external referenced class [«dataType» Real] [/req/UML/integration]
Error: Missing dependency for package [«» ISO19107] (or any of its subpackages) containing external referenced class [«» GM_Solid] [/req/UML/integration]
Error: Missing dependency for package [«applicationSchema» Datatyper_19103CSLv4.0] containing external referenced class [«dataType» Date] [/req/UML/integration]
Error: Dependency to package [«applicationSchema» Datatyper_19103CSLv4.0] (or any of its superpackages) containing element [«dataType» CharacterString] is not shown in any package diagram [/krav/17]
Error: Dependency to package [«» Generelle datatyper] (or any of its superpackages) containing element [«dataType» Link] is not shown in any package diagram [/krav/17]
Error: Dependency to package [«applicationSchema» Datatyper_19103CSLv4.0] (or any of its superpackages) containing element [«dataType» Real] is not shown in any package diagram [/krav/17]
Error: Dependency to package [«» ISO19107] (or any of its superpackages) containing element [«» GM_Solid] is not shown in any package diagram [/krav/17]
Error: Dependency to package [«applicationSchema» Datatyper_19103CSLv4.0] (or any of its superpackages) containing element [«dataType» Date] is not shown in any package diagram [/krav/17]
Error: Dependency to package [«applicationSchema» Datatyper_19103CSLv4.0] (or any of its superpackages) containing element [«dataType» CharacterString] is not shown in any package diagram [/krav/21]
Error: Dependency to package [«» Generelle datatyper] (or any of its superpackages) containing element [«dataType» Link] is not shown in any package diagram [/krav/21]
Error: Dependency to package [«applicationSchema» Datatyper_19103CSLv4.0] (or any of its superpackages) containing element [«dataType» Real] is not shown in any package diagram [/krav/21]
Error: Dependency to package [«» ISO19107] (or any of its superpackages) containing element [«» GM_Solid] is not shown in any package diagram [/krav/21]

**Comment by aatjora** [comment]
Bruke funksjonen "isWellKnownType" for å filtrere dette.

**Comment by magnusKarge** [comment]
fixed in #143
