### ISSUE TITLE
Antagelse om ApplicationSchema som startpakke

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#17]
Siden vi i framtiden også skal sjekke mot 19103, foreslår jeg å fjerne rutinen som sjekker at startpakke er ApplicationSchema ved oppstart.  Denne kan kjøres ved starten av selve valideringen og eventuelt gi feilmelding ved sjekk mot SOSI eller 19109.
Foreslår at en pakke uavhengig av stereotype må være startobjekt.
Rutiner som i dag "antar" at startpakke er applikasjonsskjema må lempe på antagelsen.

**Comment by magnusKarge** [comment]
implementert per 11.3.
