### ISSUE TITLE
Dersom testvinduet er oppe, merkes ikke endringer i tagger på pakken

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#19]
Dersom valideringsvinduet er oppe, vil testene ikke få med seg forandringer i tagger på pakken.  
Bør ses på siden dette kan skape litt forvirring siden man får samme feilmelding etter å ha rettet på taggene.  (Kan virke noe forvirrende...)
Antagelig noe som må fixes i hovedløkka.

**Comment by magnusKarge** [comment]
løst i pull request #81
