### ISSUE TITLE
All output fra EA må være i utf-8

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#21]
Mange norske og samiske tegn blir korrekte i iso8859-1 eller windows-1252 men det er også flere samiske som blir ødelagte. Bruk av klippebord kan også introdusere slike tegnsettfeil.

**Comment by magnusKarge** [comment]
Verktøyet støtter UTF8 (spesielt alle norske samiske tegn) når elementene vises i loggvinduet. Klipp- og limfunksjon inn i eksterne verktøy (notepad, notepad++, word...) kan vi ikke garantere for. Dette kan være avhengig av konfigurasjonen til pcen på brukersiden.
