### ISSUE TITLE
Falsk positiv på koder

### ISSUE THREAD

**Issue by toreJohnsen** [kartverket/SOSIModelValidationAddIn#29]
Error: Class [«CodeList» kodeliste] has unknown type for attribute [kode1 : ]. [/req/uml/profile & krav/25 & krav/22]

Denne bør vel utelate å teste på kodelister?

**Comment by magnusKarge** [comment]
muligens fixed --> test og lukk issue

**Comment by toreJohnsen** [comment]
Testet 15.03.2019 - ser ut til å være fikset
