### ISSUE TITLE
Tilbakemelding til bruker (dagens "debugmeldinger")

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#48]
Ta det som nå er "debug"-meldinger som viser hvilket element som undersøkes og skriv dette til et eget "informasjonsområde" i vinduet.
Brukeren vil dermed få tilbakemelding om at "noe skjer" uten at det kommer i sluttrapporten, noe som kan være kjekt dersom det tar lang tid mellom hver error/warning.

Etterhvert kan vi kanskje også utvide til å vise hvilken sjekk som til en hver tid utføres.

**Comment by aatjora** [comment]
Har lagt funksjonalitet inn i pull request #68.

**Comment by magnusKarge** [comment]
implemented in #68
