### ISSUE TITLE
krav 17 og 21 - opprettelse av packagesToBeReferencedPackageIDList

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#54]
Grunnet overføring av skriptet blir lista packagesToBeReferencedPackageIDList generert i req/uml/integration-sjekken.

Denne må flyttes ut grunnet mulighet til "rene" 19103-krav og fordi req/uml/integration ikke kjører dersom startpakken ikke er ApplicationSchema.

Dersom det testes mot 19109 eller sosi, skal oppbyggingen fungere som før, dvs dersom det er et applicationschema "over" pakken med elementet, er det applicationschema som skal refereres.
Dersom det testes mot 19103-regler skal ikke hensyn til applicationschema tas, dvs enhver referanse mot pakken eller overpakker er gyldig.

**Comment by magnusKarge** [comment]
fixed in #63
