### ISSUE TITLE
/krav/navning - utslag på koder

### ISSUE THREAD

**Issue by toreJohnsen** [kartverket/SOSIModelValidationAddIn#74]
Den burde kanskje ikke slå ut på "kodenavn". Vi må diskutere kravteksten.

/krav/navning – Navn på egenskaper, roller, operasjoner og parametere skal starte med
liten bokstav, og så fortsette med stor bokstav på hvert nytt ord (med
unntak av konstruktøroperasjoner som har samme navn som klassen).
Navn på pakker, klasser og assosiasjoner skal starte med stor bokstav.
(Fra ISO 19103:2015 Anbefaling 11, se også /krav/6)

**Comment by magnusKarge** [comment]
enig, testen slås av for kodenavn

**Comment by magnusKarge** [comment]
Dette medfører at vi p.t. ikke får utslag på kodenavn med stor forbokstav selv om vi har krav 6:

> /krav/6
> Navn på koder skal være mnemoniske (forståelige/huskbare), følge navnereglene for egenskapsnavn og de skal være uten skilletegn og spesialtegn.

Kent 1: Sjekk at krav/6 i 5.1 tar med unntaket for kjente egennavn som i krav/7
Kent 2: Implementer test på stor forbokstav som en del av krav/6, men med status "Warning" "...check if <codename> is a proper noun.".
