### ISSUE TITLE
optionX eller krav/6 er broken

### ISSUE THREAD

**Issue by toreJohnsen** [kartverket/SOSIModelValidationAddIn#76]
Får samme resultat på Kommunenummer kodelisten om haken er på eller av

**Comment by toreJohnsen** [comment]
Tror requirement6.vb må skrives om til å bruke variabel "checkAllCodeNames" i stedet for "optionX" ??!

**Comment by KentJonsrud** [comment]
Ved Test on all.. på: kommer melding om at Kommunenummer ikke testes mot /krav/6 men bruker masse tid på alle kodene likevel. Fylkesnummer testes, som forventet.
ved Test on all.. av: kommer samme melding. 
Ønske: tekstfelt med Kommunenummer og Fylkesnummer utfylt som initialverdi, og med mulighet for å endre/legge til andre kodelister.

**Comment by KentJonsrud** [comment]
Meldingen:
Info: Class [Kommunenummer] was not tested against /krav/6
drukner litt, så hvis det ikke testes noe må vi gi en mer stringent og tydelig melding helt til slutt:
Exception: CodeLists not confirmed to follow the standard: 
Kommunenummer, Fylkesnummer, Fartsgrense, Vegklasse

**Comment by magnusKarge** [comment]
Åsmund undersøker om det er forsvarlig tidsbruk å åpne for at brukerne kan putte andre kodelister inn i unntakslista.
