### ISSUE TITLE
støy fra /req/UML/intergration

### ISSUE THREAD

**Issue by KentJonsrud** [kartverket/SOSIModelValidationAddIn#78]
Bør vi rydde opp i modellregisteret slik at slike meldinger kan bli borte?

![image](https://user-images.githubusercontent.com/15031590/59583954-12da9d80-90dd-11e9-9769-e8ba223b8925.png)

**Comment by magnusKarge** [comment]
Ingen endringer før ev. innhold i modellregisteret  er på plass/fjernet.

**Comment by magnusKarge** [comment]
fixed in #142 

støy er borte, vi ble enige om at vi ikke tester req/UML/integration mot kjente typer. Dette betyr også at vi foreløpig ikke har ryddet opp i modellregister

**Comment by KentJonsrud** [comment]
need for tidyup is reduced or removed
