### ISSUE TITLE
Crash - varslet av Knut J.  (epost 2019-11-21 klokka 0910)

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSIModelValidationAddIn#90]
Hei,

Jeg får feilen når jeg kjører validering av noen pakker i et digert EAP-prosjekt som jeg helst ikke vil dele. Inneholder mye rart, duplikater og ting under arbeid. Har en mistanke om at det kan være årsaken. Går bra når jeg kopierer spesifikke applikasjonsskjema over i et annet prosjekt og kjører der. 

Her er hele feilmeldingen:

Se slutten av denne meldingen for detaljert informasjon om aktivering av 
JIT-feilsøking (Just In Time) i stedet for denne dialogboksen.

************** Unntakstekst **************
System.Runtime.InteropServices.COMException (0x80040000): Can't find matching ID
   ved EA.IDualRepository.GetElementByID(Int32 ElementID)
   ved SOSIModelValidation.ModelValidation.reqUMLIntegrationPackagesToBeReferenced(String ruleString)
   ved SOSIModelValidation.ModelValidation.reqUMLIntegration(Package thePackage)
   ved SOSIModelValidation.ModelValidation.RunValidation()
   ved SOSIModelValidation.SOSIModelValidationWindow.ButtonRun_Click(Object sender, EventArgs e)
   ved System.Windows.Forms.Control.OnClick(EventArgs e)
   ved System.Windows.Forms.Button.OnClick(EventArgs e)
   ved System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   ved System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   ved System.Windows.Forms.Control.WndProc(Message& m)
   ved System.Windows.Forms.ButtonBase.WndProc(Message& m)
   ved System.Windows.Forms.Button.WndProc(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   ved System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Innlastede samlinger **************
mscorlib
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.3468.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
SOSIModelValidation
    Samlingsversjon: 1.0.0.0
    Win32-versjon: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Kartverket/SOSIModelValidation.dll
----------------------------------------
Microsoft.VisualBasic
    Samlingsversjon: 10.0.0.0
    Win32-versjon: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.3468.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
   Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CustomMarshalers
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
mscorlib.resources
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_no_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Samlingsversjon: 4.0.0.0
    Win32-versjon: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_no_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-feilsøking **************
Når du skal aktivere JIT-feilsøking (Just In Time), må .config-filen for dette
programmet eller datamaskinen (machine.config) ha
jitDebugging-verdien angitt i delen system.windows.forms.
Programmet må også kompileres med feilsøking
aktivert.

For eksempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Når JIT-feilsøking er aktivert, blir alle ubehandlede unntak
sendt til JIT-feilsøkingsprogrammet som er registrert på datamaskinen,
i stedet for å bli behandlet av denne dialogboksen.

/Knut

**Comment by aatjora** [comment]
reqUMLIntegration og tilhørende rutiner er det vel jeg som står bak.  
Setter meg selv på denne i første omgang.

**Comment by toreJohnsen** [comment]
Trigges også på krav/17 ved kjøring på pakke uten ApplicationSchema stereotype
(pakke med mye rart i seg)

**Comment by magnusKarge** [comment]
minste krav til løsning: pakke alt inn i en stor try-catch-blokk og komme med en "critical failure"-melding samt anbefaling om å kjøre EA-repair og link til GitHub og oppfordring om å legge til ny issue.

**Comment by magnusKarge** [comment]
fixed in #103
